### ISSUE TITLE
Poor Error Handling

### ISSUE THREAD

**Issue by LavishSwarnkar** [Hey-Deepak/MyChat#23]
Currently if any exception occurs in ViewModel, then the app crashes, which is bad experience for user. User must be notified of the error.
In case of error, dialog should appear displaying the error message to user & an optional Retry button (if applicable).
You can use flow to emit ErrorUiEvent to the Activity & then activity can display the dialog.

**Comment by Hey-Deepak** [comment]
This is also tackled.
