### ISSUE TITLE
Login errors not displayed

### ISSUE THREAD

**Issue by LavishSwarnkar** [Hey-Deepak/MyChat#24]
https://github.com/Hey-Deepak/MyChat/blob/e55ca2852817c413f1d5ec7082f41c4f8a59d5af/app/src/main/java/com/dc/mychat/MainActivity.kt#L79-L82

For login, you have handled only success case & left the failure case unhandled (else block). That's very optimistic approach. Anything may go wrong while Login. such errors must be reported to the user.

**Comment by Hey-Deepak** [comment]
Like No Internet connection etc.

**Comment by Hey-Deepak** [comment]
Here I only added latest Error message for Display

**Comment by LavishSwarnkar** [comment]
This issue is not yet fixed. You haven't handled else case!

**Comment by Hey-Deepak** [comment]
I guess Now tackled.

**Comment by Hey-Deepak** [comment]
Sorted
