### ISSUE TITLE
Why create a new reference to exceptionHandler in other ViewModels?

### ISSUE THREAD

**Issue by LavishSwarnkar** [Hey-Deepak/MyChat#27]
https://github.com/Hey-Deepak/MyChat/blob/ea3d0b1516f31c8a39b5b9e9e725e9798422d845/app/src/main/java/com/dc/mychat/ui/viewmodel/ProfileViewModel.kt#L24

**Comment by Hey-Deepak** [comment]
Just for clarity or want to pass with their view model name for better understanding.
We can directly pass this to launch.
What you want?

**Comment by Hey-Deepak** [comment]
Sorted.
