### ISSUE TITLE
FCMReceiverService : Using Utils instead of LocalRepository to read from prefs

### ISSUE THREAD

**Issue by LavishSwarnkar** [Hey-Deepak/MyChat#28]
https://github.com/Hey-Deepak/MyChat/blob/ea3d0b1516f31c8a39b5b9e9e725e9798422d845/app/src/main/java/com/dc/mychat/other/fcm/FCMReceiverService.kt#L38

**Comment by Hey-Deepak** [comment]
Local Repository function is suspended and can't be called in On message received function because it is non suspended function.
So I went with this Util function.

**Comment by Hey-Deepak** [comment]
What approach should I take?
I am getting crashes when I use coroutine in service.
I can't change onMessage because it is override.

**Comment by Hey-Deepak** [comment]
stantiationException: java.lang.Class<com.dc.mychat.other.fcm.FCMReceiverService> has no zero argument constructor

this is error look like. My DI is not able to find localRepository instance.

**Comment by Hey-Deepak** [comment]
Problem Solved. It was due to Dependency Injection
