### ISSUE TITLE
Inifinite loader : Send new message while offline

### ISSUE THREAD

**Issue by LavishSwarnkar** [Hey-Deepak/MyChat#29]
Adding a check for internet connection can prevent this!

**Comment by Hey-Deepak** [comment]
I tried some ways but not working due to suspend function.
My whole coroutine will stop for moment when I call for network request.
How I can create an error ? Problem here is I am not receiving TimeOut exception from firebase

**Comment by Hey-Deepak** [comment]
Sorted.
