### ISSUE TITLE
UI hangs - no pogress indicator when uploading image & creating profile

### ISSUE THREAD

**Issue by LavishSwarnkar** [Hey-Deepak/MyChat#9]

**Comment by Hey-Deepak** [comment]
Half problem solved.
I don't know why loader is not showing when I send msg although my state is changing.

**Comment by Hey-Deepak** [comment]
Problem Solved (LaunchEffect needed).
Review and try to merge it.
Code in Notification Branch.
In notification branch loading and  notification issue solved
